version: "3"

services:

  proxy:
    image: vfarcic/docker-flow-proxy:1.346
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
      - proxy2
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - CERTS=STAR_overture_barco_com.pem
      - MODE=swarm
      - TIMEOUT_CLIENT=60
      - TIMEOUT_CONNECT=10
      - TIMEOUT_HTTP_REQUEST=10
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener:1.34
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  proxy:
    external: true
  proxy2:
    external: true