version: '3'

services:
  whoami:
    image: jwilder/whoami
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=whoami.domain.com
        - com.df.servicePath=/
        - com.df.port=8080
        - com.df.httpsOnly=true
    networks:
        proxy2:
networks:
  proxy2:
    external: true