version: "3.1"

services:
  registry:
    image: registry:2.6.1
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          memory: 100M

  master:
    image: jenkinsci/jenkins:${TAG:-lts-alpine}
    ports:
      - "50000:50000"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      - proxy
      - ci
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins
        - com.df.port=8080

  agent:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://master:8080/jenkins -labels 'docker' -executors 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci
    secrets:
      - jenkins-user
      - jenkins-pass
    deploy:
      mode: global

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

networks:
  proxy:
    external: true
  ci:
    driver: overlay