version: '3.1'

services:
  postgresql-master:
    image: 'bitnami/postgresql:9.6'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=${PG_REPL_PASS:-repl_password}
      - POSTGRESQL_USERNAME=odoo
      - POSTGRESQL_PASSWORD=${PG_ODOO_PASS:-odoo_pass}
      - POSTGRESQL_DATABASE=odoo
    networks:
      - postgres
    deploy:
      replicas: 1
  postgresql-slave:
    image: 'bitnami/postgresql:9.6'
    networks:
      - postgres
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=${PG_REPL_PASS:-repl_password}
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    deploy:
      replicas: 1
  pgadmin:
    image: fenglc/pgadmin4:1.4
    networks:
      - postgres
      - proxy
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/pgadmin
        - com.df.port=5050

networks:
  postgres:
    external: true
  proxy:
    external: true