sudo: required

language: ruby

services:
  - docker

before_install:

script:
  - go test -v ./...

after_success:
  - docker run --rm -v $PWD:/usr/src/myapp -w /usr/src/myapp -v $GOPATH:/go golang:1.6 go build -v -o docker-flow-proxy
