site_name: Docker Flow: Proxy
site_url: https://github.com/vfarcic/docker-flow-proxy
repo_url: https://github.com/vfarcic/docker-flow-proxy.git
docs_dir: articles
pages:
- Home: index.md
- Modes:
    - The Swarm Mode (Docker 1.12+) with automatic configuration: swarm-mode-listener.md
    - The Swarm Mode (Docker 1.12+) with manual configuration: swarm-mode.md
    - The Default Mode: The Default Mode
