version: "3"

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 2
      resources:
        reservations:
          memory: 50M

  docs:
    image: vfarcic/docker-flow-proxy-docs
    networks:
      - proxy
    deploy:
      labels:
        - com.df.distribute=true
        - com.df.notify=true
        - com.df.port=80
        - com.df.serviceDomain=proxy.dockerflow.com,dockerflow.com
        - com.df.servicePath=/
      replicas: 2
      resources:
        reservations:
          memory: 50M

networks:
  proxy:
    external: true
