version: "3.3"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    environment:
      - cluster.name=docker-es-cluster
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - TZ=Europe/Helsinki
    networks:
      - logging_nw
    # deploy:
    #   resources:
    #     reservations:
    #       memory: 1000M
    #     limits:
    #       memory: 1500M

  # elasticsearch2:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
  #   environment:
  #     - cluster.name=docker-es-cluster
  #     - xpack.security.enabled=false
  #     - ES_JAVA_OPTS=-Xms512m -Xmx512m
  #     - TZ=Europe/Helsinki
  #     - discovery.zen.ping.unicast.hosts=elasticsearch
  #   deploy:
  #     resources:
  #       reservations:
  #         memory: 1000M
  #       limits:
  #         memory: 1500M
  #   networks:
  #     - logging_nw

  # logstash:
  #   image: docker.elastic.co/logstash/logstash-oss:6.2.3
  #   volumes:
  #     - ./LogstashConfigFiles:/usr/share/logstash/pipeline:ro
  #     - /etc/localtime:/etc/localtime
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   networks:
  #     - logging_nw
  #   depends_on:
  #     - elasticsearch

  vnext-backend-beats-logfilereader:
    image: docker.elastic.co/beats/filebeat:6.2.3
    volumes:
      - ./FileBeatConfigFiles/app-backend.yml:/usr/share/filebeat/filebeat.yml:ro
      - /etc/localtime:/etc/localtime
    networks:
      - logging_nw
    depends_on:
      - logstash
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    networks:
      - logging_nw
      - proxy
    environment:
      - xpack.security.enabled=false
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - ./Kibana/kibana.yml:/etc/kibana/kibana.yml
    deploy:
      labels:
        - com.df.aclName=proxyPriority
        - com.df.notify=true
        - com.df.distribute=true
        # - com.df.servicePath=/,/api
        - com.df.port=5601
        - com.df.srcPort=5601
        - com.df.serviceDomainAlgo=hdr_beg(host)
        - com.df.serviceDomain=mysite.com

networks:
  proxy:
    external: true
  logging_nw:
