version: "3"
services:

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - service
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: postgres:9.4
    networks:
      - service
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  service:
    external: true
