version: "3"
services:

  vote:
    image: dockersamples/examplevotingapp_vote:before
    networks:
      - proxy
      - service
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.xForwardedProto=true
        - com.df.servicePath=/votes
        - com.df.reqPathSearch=/votes
        - com.df.reqPathReplace=/
        - com.df.port=80

  result:
    image: dockersamples/examplevotingapp_result:before
    networks:
      - proxy
      - service
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.xForwardedProto=true
        - com.df.servicePath=/results
        - com.df.reqPathSearch=/results
        - com.df.reqPathReplace=/
        - com.df.port=80

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - service
    deploy:
      replicas: 1
      labels: [APP=VOTING]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true
  service:
    external: true