version:  '3'
services:

  varnish:
    image: lhenry/test:latest
    environment:
     - VARNISH_BACKEND=nginx_app
     - CACHE_SIZE=2GB
    networks:
     - proxy
     - swarmnet
    deploy:
      replicas: 1
#      placement:
#        constraints: [node.role != manager]
      resources:
        limits:
          memory: 3G
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
       - com.df.notify=true
       - com.df.distribute=true
       - com.df.serviceDomain=default.test.com
       - com.df.servicePath.1=/
       - com.df.srcPort.1=80
       - com.df.port.1=80
       - com.df.servicePath.2=/
       - com.df.srcPort.2=443
       - com.df.port.2=443

  app:
    image: nginx
    networks:
     - proxy
    deploy:
      replicas: 1
#      placement:
#        constraints: [node.role != manager]
      resources:
        limits:
          memory: 4G
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  proxy:
    external: true
  swarmnet:
    external: true
